import React from 'react';
import { Icon } from './Icon';

interface FinalResponseProps {
  content: string;
}

export const FinalResponse: React.FC<FinalResponseProps> = ({ content }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mt-8 mb-20 animate-in slide-in-from-bottom-6 duration-700 fade-in">
      {/* Header */}
      <div className="flex items-center justify-between mb-4 px-2">
        <div className="flex items-center gap-3">
          <div className="relative">
            <div className="absolute inset-0 bg-indigo-500 blur-lg opacity-40 rounded-full animate-pulse-slow"></div>
            <div className="relative w-10 h-10 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/30 border border-white/20">
              <Icon name="Check" size={20} className="text-white" />
            </div>
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">Final Report</h2>
            <p className="text-xs text-indigo-300 font-mono uppercase tracking-wider">Mission Complete</p>
          </div>
        </div>

        <button 
          onClick={handleCopy}
          className="flex items-center gap-2 text-xs font-medium bg-surfaceHighlight hover:bg-white/10 text-zinc-400 hover:text-white px-3 py-1.5 rounded-lg border border-white/5 transition-all"
        >
          <Icon name={copied ? "Check" : "Copy"} size={14} />
          {copied ? "Copied" : "Copy Result"}
        </button>
      </div>
      
      {/* Content Box */}
      <div className="relative group">
        <div className="absolute -inset-0.5 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-2xl opacity-20 blur group-hover:opacity-30 transition duration-1000"></div>
        <div className="relative bg-[#121215] border border-white/10 rounded-2xl p-6 md:p-8 shadow-2xl backdrop-blur-sm">
          
          <div className="markdown-content">
            <div className="whitespace-pre-wrap text-zinc-200 leading-7 font-light">
              {content}
            </div>
          </div>

          <div className="mt-8 pt-6 border-t border-white/5 flex items-center justify-between text-[10px] text-zinc-600 font-mono uppercase tracking-widest">
            <span>Generated by Nexus AI</span>
            <span>{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>
    </div>
  );
};